version: '3.8'

services:

  appseed-app:
    container_name: appseed_app
    restart: always
    build: .
    networks:
      - web_network
    volumes:
      - statics:/app/static 

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:1.13.9-alpine"
    ports:
      - "127.0.0.1:2828:5085"
    volumes:
      - statics:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - appseed-app

networks:
  web_network:
    driver: bridge
  
volumes:
  statics: 
