# Generated by Django 5.0.1 on 2024-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
