# Generated by Django 5.0.1 on 2024-03-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.CharField(default='000000000000', max_length=11),
        ),
    ]
