# Generated by Django 5.0.1 on 2024-03-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options_alter_usuario_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.CharField(default='0', max_length=11),
        ),
    ]
