# Generated by Django 5.0.1 on 2024-03-08 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad', models.IntegerField()),
                ('fecha', models.DateTimeField(null=True)),
                ('transporte', models.CharField(choices=[('AV', 'Avión'), ('TR', 'Tren'), ('BU', 'Omnibús')], max_length=20)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='reservas.ruta')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origenes', to='reservas.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Viajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pasaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.pasaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.viajero')),
            ],
        ),
    ]
