# Generated by Django 5.0.1 on 2024-03-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('proxima', 'Próxima'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='activa', max_length=20),
        ),
    ]
