# Generated by Django 5.0.1 on 2024-03-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_viaje_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='lugar',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
